# code for the factory

# Stage 1.1: Trigger provisioning of device
#start - contact device and ask for DID

# Stage 1.3: VC transfer to device


# The following was generated by Claude LLM
from flask import Flask, request, jsonify # to facilitate http requests
import didkit # for verifiable credentials
from datetime import datetime, timezone # for timestamps
import json

app = Flask(__name__)

# Manufacturer's own key pair (generated once at startup)
manufacturer_jwk = None
manufacturer_did = None

# In-memory storage for device data
devices = {}

# initialise manufacturer
def init_manufacturer(man_id):
    manufacturer_id = man_id # for testing
    """Initialize the manufacturer's identity"""
    global manufacturer_jwk, manufacturer_did
    print("\n=== Initializing Manufacturer Identity ===")
    manufacturer_jwk = didkit.generateEd25519Key()
    manufacturer_did = didkit.keyToDID("key", manufacturer_jwk)
    print(f"Manufacturer DID: {manufacturer_did}")
    print("=" * 50 + "\n")

@app.route('/api/devices/register', methods=['POST'])
def register_device():
    """Register a new device with its public key and DID, then issue a credential"""
    data = request.json # received from device
    device_id = data.get('device_id')
    public_key_jwk = data.get('public_key_jwk')
    did = data.get('did')
    verification_method = data.get('verification_method')
    
    if not device_id or not public_key_jwk or not did:
        return jsonify({'error': 'device_id, public_key_jwk, and did required'}), 400
    
    print(f"\n=== Registering Device: {device_id} ===")
    print(f"Device DID: {did}")
    
    # Store device info
    devices[device_id] = {
        'device_id': device_id,
        'public_key_jwk': public_key_jwk,
        'public_key': public_key_jwk,
        'did': did,
        'verification_method': verification_method,
        'registered_at': datetime.now().isoformat(),
        'status': 'active'
    }
    
    # Issue a credential to the device certifying its identity
    print(f"Issuing device credential...")

    
    #generate credential
    device_credential = {
        "@context": [
            "https://www.w3.org/2018/credentials/v1",
            #device_context
        ],
        "type": ["VerifiableCredential", "DeviceRegistrationCredential"],
        "issuer": manufacturer_did,
        "issuanceDate": datetime.now(timezone.utc).isoformat().replace('+00:00', 'Z'),
        "credentialSubject": {
            #credentialSubject.id
            "id": did,
            #"deviceId": device_id,
            #"status": "active"
        }
    }
    
    proof_options = {
        "proofPurpose": "assertionMethod",
        "verificationMethod": didkit.keyToVerificationMethod("key", manufacturer_jwk)
    }
    
    try:
        # Sign the credential with manufacturer's key
        signed_credential = didkit.issueCredential(
            json.dumps(device_credential),
            json.dumps(proof_options),
            manufacturer_jwk
        )
        
        credential_dict = json.loads(signed_credential)
        devices[device_id]['manufacturer_credential'] = credential_dict
        
        print(f"✓ Device credential issued successfully")
        print("=" * 50 + "\n")
        
        return jsonify({
            'message': 'Device registered successfully',
            'device': devices[device_id],
            'credential': credential_dict
        }), 201
        
    except Exception as e:
        print(f"✗ Error issuing credential: {e}")
        return jsonify({
            'error': f'Registration successful but credential issuance failed: {str(e)}',
            'device': devices[device_id]
        }), 500

@app.route('/api/devices/<device_id>/verify-credential', methods=['POST'])
def verify_credential(device_id):
    """Verify a signed credential from a device"""
    if device_id not in devices:
        return jsonify({'error': 'Device not registered'}), 404
    
    data = request.json
    credential = data.get('credential')
    
    # In a real implementation, you would verify the credential here
    # using didkit.verify_credential()
    
    return jsonify({
        'message': 'Credential received',
        'device_id': device_id,
        'verification_status': 'accepted'
    }), 200

@app.route('/api/devices', methods=['GET'])
def list_devices():
    """List all registered devices"""
    return jsonify({'devices': list(devices.values())}), 200

@app.route('/api/devices/<device_id>', methods=['GET'])
def get_device(device_id):
    """Get device details including public key"""
    if device_id not in devices:
        return jsonify({'error': 'Device not found'}), 404
    
    return jsonify({'device': devices[device_id]}), 200

if __name__ == '__main__':
    print("Starting Manufacturer API Server on http://localhost:5000")
    print("Install dependencies: pip install flask didkit")
    print("\nAvailable endpoints:")
    print("  POST /api/devices/register")
    print("  POST /api/devices/<device_id>/verify-credential")
    print("  GET  /api/devices")
    print("  GET  /api/devices/<device_id>")
    
    # Initialize manufacturer's identity
    init_manufacturer(man_id='MANUFACTURER-01')
    
    app.run(debug=False, port=5000, use_reloader=False)