# code for the factory

# Stage 1.1: Trigger provisioning of device
#start - contact device and ask for DID

# Stage 1.3: VC transfer to device


# The following was generated by Claude LLM
from flask import Flask, request, jsonify # to facilitate http requests
from datetime import datetime
import json

app = Flask(__name__)

# In-memory storage for device data
devices = {}

@app.route('/api/devices/register', methods=['POST'])
def register_device():
    """Register a new device with its DID and public key"""
    data = request.json
    device_id = data.get('device_id')
    did = data.get('did')
    public_key = data.get('public_key_jwk')
    verification_method = data.get('verification_method')
    
    if not device_id or not did:
        return jsonify({'error': 'device_id and did required'}), 400
    
#    if devices[device_id]:
#        return jsonify({'error': 'device_id already registered'}), 400
    
    devices[device_id] = {
        'device_id': device_id,
        'did': did,
        'public_key': public_key,
        'verification_method': verification_method,
        'registered_at': datetime.now().isoformat(),
        'status': 'active'
    }
    
    return jsonify({
        'message': 'Device registered successfully',
        'device': devices[device_id]
    }), 201

@app.route('/api/devices/<device_id>/verify-signature', methods=['POST'])
def verify_signature(device_id):
    """Verify a signed message from a device"""
    if device_id not in devices:
        return jsonify({'error': 'Device not registered'}), 404
    
    data = request.json
    signed_message = data.get('signed_message')
    
    # CLLM: In a real implementation, you would verify the signature here
    # CLLM: using the device's public key stored in devices[device_id]
    # EL: This is where VCs come in
    
    return jsonify({
        'message': 'Signature verification endpoint',
        'device_id': device_id,
        'verification_status': 'pending'
    }), 200

@app.route('/api/devices', methods=['GET'])
def list_devices():
    """List all registered devices"""
    return jsonify({'devices': list(devices.values())}), 200

@app.route('/api/devices/<device_id>', methods=['GET'])
def get_device(device_id):
    """Get device details including DID and public key"""
    if device_id not in devices:
        return jsonify({'error': 'Device not found'}), 404
    
    return jsonify({'device': devices[device_id]}), 200

if __name__ == '__main__':
    print("Starting Manufacturer API Server on http://localhost:5000")
    print("Install dependencies: pip install flask didkit")
    app.run(debug=True, port=5000)